# Generated by Django 5.1 on 2024-09-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_transaction_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelTable(
            name='paymentdetail',
            table='PaymentDetail',
        ),
    ]
