# Generated by Django 5.1 on 2024-09-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_ticket_number_alter_paymentdetail_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('adult_count', models.IntegerField()),
                ('adult_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('child_count', models.IntegerField()),
                ('child_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('student_count', models.IntegerField()),
                ('student_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_method', models.CharField(max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
