# Generated by Django 5.1.1 on 2024-09-08 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_ticket_delete_ticket_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentDetail',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
