# Generated by Django 5.1.1 on 2024-09-23 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_ticketsale'),
        ('app', '0005_delete_paymentdetail_delete_transaction'),
    ]

    operations = [
    ]
